package com.ysten.videoplus.client.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ysten.videoplus.client.module.vod.bean.TestBean;
import com.ysten.videoplus.client.module.vod.bean.VideoBean;

import com.ysten.videoplus.client.greendao.TestBeanDao;
import com.ysten.videoplus.client.greendao.VideoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testBeanDaoConfig;
    private final DaoConfig videoBeanDaoConfig;

    private final TestBeanDao testBeanDao;
    private final VideoBeanDao videoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        videoBeanDaoConfig = daoConfigMap.get(VideoBeanDao.class).clone();
        videoBeanDaoConfig.initIdentityScope(type);

        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);
        videoBeanDao = new VideoBeanDao(videoBeanDaoConfig, this);

        registerDao(TestBean.class, testBeanDao);
        registerDao(VideoBean.class, videoBeanDao);
    }
    
    public void clear() {
        testBeanDaoConfig.clearIdentityScope();
        videoBeanDaoConfig.clearIdentityScope();
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

    public VideoBeanDao getVideoBeanDao() {
        return videoBeanDao;
    }

}
